#include<stdio.h>
int main()
{
    int n,j,arr[100],i,k,p,sp,c=0,d,np,e;
    scanf("%d",&n);
    for(i=0;i<n;i++)
    {
        scanf("%d",&arr[i]);
    }
    for(i=0;i<n;i++)
    {
        for(j=arr[i];j>=arr[i]-10;j--)
        {
            c=0;
            for(k=1;k<=j;k++)
            {
                if(j%k==0)
                {
                    c++;
                }
            }
            if(c==2)
            {
                np=j;
                d=arr[i]-np;
                break;
            }
        }
        for(j=arr[i];j<=arr[i]+10;j++)
        {
            c=0;
            for(k=1;k<=j;k++)
            {
                if(j%k==0)
                {
                    c++;
                }
            }
            if(c==2)
            {
                sp=j;
                e=sp-arr[i];
                break;
            }
        }
        if(d<e || d==e)
        {
            printf("%d
",np);
        }
        else
        {
            printf("%d
",sp);
        }
    }
}